"""change_id_columns_to_bigint

Revision ID: 0343cc2f5c42
Revises: 4663849f7a69
Create Date: 2025-03-25 11:57:49.992860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0343cc2f5c42'
down_revision = '4663849f7a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('company_relationships', schema=None) as batch_op:
        batch_op.alter_column('source_company_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('target_company_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('data_sharing_policies', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('data_type_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('data_sharing_third_parties', schema=None) as batch_op:
        batch_op.alter_column('policy_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('company_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('data_types', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('token_packages', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('data_type_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('company_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('user_profile_preferences', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('user_profile_preferences', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('company_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
        batch_op.alter_column('data_type_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('token_packages', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('data_types', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('data_sharing_third_parties', schema=None) as batch_op:
        batch_op.alter_column('company_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('policy_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('data_sharing_policies', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('data_type_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('company_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('company_relationships', schema=None) as batch_op:
        batch_op.alter_column('target_company_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.alter_column('source_company_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
