name: Deploy to AWS

on:
  push:
    branches:
      - main
      - production
  pull_request:
    branches:
      - main
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies (Frontend)
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install EB CLI
        run: |
          pip install awsebcli
          pip install awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3 (Frontend)
        run: |
          aws s3 sync build/ s3://${{ secrets.S3_BUCKET_NAME }} --delete
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

      - name: Deploy to Elastic Beanstalk (Backend)
        working-directory: ./backend
        run: |
          eb init -p python-3.10 data-privacy-app --region ${{ secrets.AWS_REGION }}
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            eb deploy data-privacy-dev
          elif [[ "${{ github.ref }}" == "refs/heads/production" ]]; then
            eb deploy data-privacy-prod
          fi 